"""empty message

Revision ID: 29a5c7640910
Revises: 41ee6b4dd0dc
Create Date: 2024-11-17 08:37:46.982867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a5c7640910'
down_revision = '41ee6b4dd0dc'
branch_labels = None
depends_on = None


def upgrade():

    op.execute("DROP TYPE IF EXISTS user_roles_enum")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('Learner', 'Contributor', 'Admin', name='user_roles_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
