"""empty message

Revision ID: 890de685394f
Revises: 2335b507b4bb
Create Date: 2024-11-18 10:17:48.078584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '890de685394f'
down_revision = '2335b507b4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')

    op.create_table('points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points_awarded', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='points_module_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='points_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='points_pkey')
    )
    # ### end Alembic commands ###
