name: CI/CD pipeline for backend development
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev
      
jobs:
  build-macos:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, macos-13, macos-12]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name:  setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.12.x'

      - name: upgrade pip
        run: 
          python -m pip install --upgrade pip
          
      - name: install dependencies
        run:
          pip install -r requirements.txt 
          
  build-linux:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
       
        
    services:
      postgres:
        image: postgres:14
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: study_platform_db
          
        ports: 
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env: 
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/study_platform_db 
      FLASK_APP: app

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name:  setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.12.x'

      - name: upgrade pip
        run: 
          python -m pip install --upgrade pip
          
      - name: install dependencies
        run:
          pip install -r requirements.txt
          
      - name: load .env file
        run:
          cat .env >> $GITHUB_ENV
          
      # - name: run migrations
      #   env:
      #     DATABASE_URL: ${{env.DATABASE_URL}}
      #   run:
      #     flask db upgrade head
          
          
        
      
    
