name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      # - name: Run Tests (Optional)
      #   run: |
      #     python -m pytest 

  merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev -X theirs -m "Automated merge from dev to main" --allow-unrelated-histories
          git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}      
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-csossa1u0jms738pdbfg/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{
                "branch": "main",  # Trigger deployment from the main branch
                "env": {
                  "DATABASE_URL": "$POSTGRES_URL"  # Passing the PostgreSQL URL to the app
                }
              }'
